site_name: Guide d'installation Arch Linux
site_url: https://vivienm.github.io/install-arch/
site_author: Vivien Maisonneuve

copyright: Vivien Maisonneuve

repo_url: https://github.com/vivienm/install-arch
repo_name: vivienm/install-arch

nav:
- Accueil: index.md
- Installation:
  - installation/preinstallation.md
  - installation/installation.md
  - installation/configuration.md
  - installation/reboot.md
- Post-installation:
  - postinstallation/boot.md
  - postinstallation/adminsys.md
  - postinstallation/optimization.md
  - postinstallation/services.md
  - postinstallation/gui.md

theme:
  name: material
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    toggle:
      icon: material/lightbulb-outline
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    toggle:
      icon: material/lightbulb
      name: Switch to light mode
  features:
  - navigation.tracking
  - navigation.tabs
  - toc.integrate
  language: fr

extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/vivienm
  - icon: fontawesome/brands/linkedin
    link: https://www.linkedin.com/in/vmaisonneuve/

markdown_extensions:
- toc:
    permalink: true
- pymdownx.highlight
- pymdownx.superfences
